# Generated by Django 3.0 on 2021-10-27 07:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20211027_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='LocationData',
        ),
    ]
