# Generated by Django 3.0 on 2021-10-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auto_20211027_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
    ]
